import PeekabooDesktop

public typealias Win11PlatformCapability = DesktopPlatformCapability
public typealias Win11PlatformInfo = DesktopPlatformInfo
public typealias Win11Display = DesktopDisplay
public typealias Win11Application = DesktopApplication
public typealias Win11Window = DesktopWindow
public typealias Win11CaptureFormat = DesktopCaptureFormat
public typealias Win11CaptureResult = DesktopCaptureResult
public typealias Win11UIAutomationStatus = DesktopUIAutomationStatus
public typealias Win11UIAutomationSnapshotScope = DesktopUIAutomationSnapshotScope
public typealias Win11UIAutomationElementSnapshot = DesktopUIAutomationElementSnapshot
public typealias Win11UIAutomationSnapshot = DesktopUIAutomationSnapshot
public typealias Win11CommandEnvelope<Payload: Encodable> = DesktopCommandEnvelope<Payload>
